name: eda
channels:
  - conda-forge
  - defaults
dependencies:
  # - jupyterlab=4.0.8
  # - jupyterlab=3.0.12
  - jupyter=1.0.0
  # - seaborn=0.11.1
  - seaborn=0.12.2
  # - pandas=1.2.3
  - pandas=1.5.3
  - pandas-profiling=3.6.3
  - pyarrow=11.0.0
  # - pip=20.3.3
  - pip=23.3.1
  # - pandas-profiling=2.11.0
  # - pandas-profiling=3.1.0
  # - pyarrow=2.0
  - pip:
      # - wandb==0.10.31
      - numpy==1.26.2
      - wandb==0.16.0
      # - numpy==1.19.5
      # - numpy==1.26.2
      # - protobuf==3.20.*