name: basic_cleaning
channels:
  - conda-forge
  - defaults
dependencies:
  - pandas=1.1.4
  - pip=20.3.3
  # - pip=23.3.1
  - mlflow=1.14.1
  - scikit-learn=0.24.1
  - matplotlib=3.2.2
  - pillow=8.1.2
  # - numpy=1.26.2
  - numpy=1.20.1
  - pip:
      - wandb==0.10.21
      # - numpy==1.24.4
      # - numpy==1.19.5
